[project]
name = "slop"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    langchain, 
    langgraph, 
    langchain_google_genai
]
